// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_6y4R0GERO39KKI4LHWDI-ijtf7SiX8',
    appId: '1:795278877436:web:00d23c71ab3bf14106ed79',
    messagingSenderId: '795278877436',
    projectId: 'meditrack-294f6',
    authDomain: 'meditrack-294f6.firebaseapp.com',
    storageBucket: 'meditrack-294f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bN7VLGuTN06D2GeYJoMWplPX-M125NI',
    appId: '1:795278877436:android:883b8aa9bb48974b06ed79',
    messagingSenderId: '795278877436',
    projectId: 'meditrack-294f6',
    storageBucket: 'meditrack-294f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6C7cNyjEPJgYHX7a5O5mvK2kVySy9Mg',
    appId: '1:795278877436:ios:10d5ba12c7c723e406ed79',
    messagingSenderId: '795278877436',
    projectId: 'meditrack-294f6',
    storageBucket: 'meditrack-294f6.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );
}
