// Mocks generated by Mockito 5.4.6 from annotations
// in meditrack/test/unit/patient_provider_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:meditrack/features/home/models/doctor.dart' as _i7;
import 'package:meditrack/features/home/models/patient.dart' as _i5;
import 'package:meditrack/features/home/services/firestore_db.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDb extends _i1.Mock implements _i3.FirestoreDb {
  MockFirestoreDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeFirebaseFirestore_0(this, Invocation.getter(#db)),
          )
          as _i2.FirebaseFirestore);

  @override
  _i4.Future<void> addPatientRecord(_i5.Patient? patient) =>
      (super.noSuchMethod(
            Invocation.method(#addPatientRecord, [patient]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getNextPatientId() =>
      (super.noSuchMethod(
            Invocation.method(#getNextPatientId, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getNextPatientId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deletePatient(String? patientId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePatient, [patientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Patient>> fetchPatientData(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPatientData, [doctorId]),
            returnValue: _i4.Stream<List<_i5.Patient>>.empty(),
          )
          as _i4.Stream<List<_i5.Patient>>);

  @override
  _i4.Future<void> saveDoctorProfile(_i7.Doctor? doctor) =>
      (super.noSuchMethod(
            Invocation.method(#saveDoctorProfile, [doctor]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Doctor?> fetchDoctorData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDoctorData, []),
            returnValue: _i4.Future<_i7.Doctor?>.value(),
          )
          as _i4.Future<_i7.Doctor?>);
}
